language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get -y install python3 python3-pip python3.4-venv python-dev
  - python3 -m venv ./venv
  - source ./venv/bin/activate
install:
  - npm install
  -  ./venv/bin/pip install --upgrade pip setuptools
  -  ./venv/bin/pip install -r requirements_dev.txt
script:
  - npm run unittest:py
  - npm run unittest:js
